config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'posts#index'

  get :log_out, to: 'sessions#destroy'

  resources :users, except: :index
  resources :posts
  resources :sessions, except: :index
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing_info.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: billing_infos
#
#  id         :bigint(8)        not null, primary key
#  last4      :string
#  country    :string
#  brand      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#

class BillingInfo < ApplicationRecord
  belongs_to :user
  validates :last4, numericality: { only_integer: true, equal_to: 4 }, presence: true
  validates :country, presence: true
  validates :brand, presence: true
end

app/models/book.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: books
#
#  id         :bigint(8)        not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string
#

class Book < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :book_users, class_name: 'User'
  
  scope :recent, -> { where('created_at > ?', 1.days.ago) } 

  validates :name, uniqueness: true, presence: true
  validates :body, presence: true
end

app/models/comment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id         :bigint(8)        not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#  post_id    :bigint(8)
#

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/image.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: images
#
#  id             :bigint(8)        not null, primary key
#  imageable_type :string
#  imageable_id   :bigint(8)
#  url            :string
#

class Image < ApplicationRecord
  mount_uploader :url, CoverUploader

  belongs_to :imageable, polymorphic: true, optional: true
  # validates :url, url: true
end

app/models/post.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#

class Post < ApplicationRecord
  max_paginates_per 20

  # belongs_to
  belongs_to :user

  # has_one
  has_one :cover, as: :imageable, class_name: 'Image', dependent: :destroy
  accepts_nested_attributes_for :cover

  # has_many
  has_many :comments, dependent: :destroy

  # through
  has_many :commentable_users, through: :comments, source: :user

  # scoped
  has_many :recent_comments,
           -> { where('created_at > ?', 10.days.ago) },
           foreign_key: :post_id,
           class_name: 'Comment'

  validates :title, uniqueness: true, presence: true
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: users
#
#  id            :bigint(8)        not null, primary key
#  username      :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  password_hash :string
#  password_salt :string
#

class User < ApplicationRecord
  attr_accessor :password

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :books, join_table: :book_users, dependent: :destroy, class_name: 'Book'

  has_one :avatar, as: :imageable, class_name: 'Image', dependent: :destroy
  has_one :billing_info, dependent: :destroy

  validates :username, uniqueness: true, presence: true
  validates :password, length: { minimum: 6 }, presence: true

  before_save :encrypt_password, if: -> { password.present? }

  def self.authenticate(username, password)
    user = find_by(username: username)

    user if user&.correct_password?(password)
  end

  def correct_password?(password)
    password_hash == BCrypt::Engine.hash_secret(password, password_salt)
  end

  private

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :user_signed_in?
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    current_user.present?
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy]

  def index
    @posts = Post.includes(@posts).page(params[:page])
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(posts_params)
    if @post.save
      redirect_to({ action: :index }, notice: 'Post was successfully saved!')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update_attributes(posts_params)
      redirect_to({ action: :index }, notice: 'Post was successfully updated!')
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to({ action: :index }, notice: 'Post was successfully deleted!')
    else
      redirect_to({ action: :index }, notice: 'Post was not deleted!')
    end
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def posts_params
    params.require(:post).permit(
      :title, :body, cover_attributes: %i[id url]
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :find_user, only: %i[show edit update]

  def show; end

  def new; end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_path, notice: t('controllers.session.create.success')
    else
      flash.now.alert = t('controllers.session.create.error')
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: t('controllers.session.destroy.success')
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: %i[show edit update destroy]

  # def index
  #   @users = User.all
  # end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
     if @user.save
       redirect_to root_path, notice: 'Signed up!'
     else
       render :new
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end


  def users_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minelochain</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'shared/navbar' %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, class: "alert alert-#{ name == :error ? 'danger' : 'success' } alert-dismissable", role: 'alert' do %>
          <button class="close" type='button' data-dismiss='alert'>
            <span aria-hidden='true'> &times; </span>
            <span class="sr-only"> Close </span>
          </button>
          <%= msg %>
        <% end %>
      <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, required: true, class: 'form-control' %>
      <small id="titleHelp" class="form-text text-danger">
        <%= @post.errors[:title].join(', ') %>
      </small>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, size: '60x12', required: true, class: 'form-control' %>
      <small id="bodyHelp" class="form-text text-danger">
        <%= @post.errors[:body].join(', ') %>
      </small>
    </div>
    <div>
      <%= f.fields_for :cover, @post.build_cover do |ff| %>
        <%= ff.label :url, 'Image' %>
        <%= ff.file_field :url %>
        <small id="bodyHelp" class="form-text text-danger">
          <%= @post.errors['cover.url'].join(', ') %>
        </small>
      <% end %>
    </div>
    <%= f.submit 'Save', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="card" style="width: 28rem;">
  <% if post.cover.present? %>
    <%= link_to post.cover.url.url, alt: 'Image', class: 'card-img-top', target: '_blank' do %>
      <%= image_tag post.cover.url.middle.url %>
    <% end %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= post.title %></h5>
    <p class="card-text"> <%= post.body %></p>
    <%= link_to 'Open', post, class: 'btn btn-primary'%>
    <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-warning'%>
    <%= link_to 'Destroy', post_path(post), method: :delete, confir: 'Are you sure?', class: 'btn btn-danger'%>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form'%>

app/views/posts/index.html.erb
<%== paginate @posts %>
<div class="card-columns" id="posts">
  <%== render @posts %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

app/views/shared/_navbar.html.erb
<!-- Grey with black text -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to t('views.shared._navbar.links.posts'), posts_path, class: 'nav-link' %>
    </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to t('views.shared._navbar.links.new_post'), new_post_path, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
  <div id="user_nav " class=" wight_log_sign">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="logged">
          Logged in as <%= current_user.username %>.
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', log_out_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/_form.html.erb
<div class= "center">
  <h1 class="sign_up"> Sign Up</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>

  <% end %>
  <div class="form-group">
    <div class="col-md-6">
      <%= f.label :username , class:"user_save" %><br />
      <%= f.text_field :username , required: true, class: "form-control" , placeholder: "Enter Your Username"%>
      <small id="titleHelp" class="form-text text-danger">
        <%= @user.errors[:username].join(', ') %>
      </small>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-6">
      <%= f.label :password, class: "but_password_save" %><br />
      <%= f.password_field :password, required: true, class: "form-control",  placeholder: "Enter Your Password"  %>
      <small id="titleHelp" class="form-text text-danger">
        <%= @user.errors[:password].join(', ') %>
      </small>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-6">
      <%= f.label :password_confirmation, class: "but_user_save_password2"  %><br/>
      <%= f.password_field :password_confirmation , required: true, class: "form-control",  placeholder: "Confirm Your Password"%>
       <small id="titleHelp" class="form-text text-danger">
         <%= @user.errors[:password_confirmation].join(', ') %>
       </small>
    </div>
  </div>
  <div class="but_data_save "><button type="submit" class="btn btn-primary col-md-3">Save Your Data</button></div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div class="card" style="width: 30rem;">
  <div class="card-body">
    <h5 class="card-title"><%= user.username %></h5>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<%= render @user %>